services:
  text_service:
    container_name: text_service
    build:
      context: ..
      dockerfile: Dockerfile
    image: text_service
    env_file:
      - ../.dev.env
    ports:
      - "8000:8000"
    command: "uvicorn application.main:create_app --host 0.0.0.0 --port 8000 --factory"
    networks:
      - backend

  taskiq-worker:
    container_name: taskiq_worker
    build:
      context: ..
      dockerfile: Dockerfile
    image: taskiq_worker
    env_file:
      - ../.dev.env
    working_dir: /app
    ports: [ ]
    command: [ taskiq, worker, -fsd, app.infra.taskiq.task_app:taskiq_broker, -w, "1", --max-fails, "1"]
    networks:
      - backend

networks:
  backend:
    driver: bridge