services:
  postgres_text:
    image: postgres:16-alpine
    container_name: pg_text
    env_file:
      - ../.dev.env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "45432:5432"
    volumes:
      - pgdata_text:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin_text:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_text
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres_text
    volumes:
      - pgadmin_text:/var/lib/pgadmin
    networks:
      - backend

  redis_text:
    image: redis:7-alpine
    container_name: redis_text
    ports:
      - "6378:6378"
    volumes:
      - redis_text:/data
    networks:
      - backend

volumes:
  pgdata_text:
  pgadmin_text:
  redis_text:

networks:
  backend:
    driver: bridge