services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    ports:
      - "9090:9090"
    command: ["--config.file=/etc/prometheus/prometheus.yaml"]
    networks:
      - backend

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./monitoring/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tmp/tempo_data
    ports:
      - "3200:3200"  # Tempo HTTP
      - "5317:4317"  # OTLP gRPC
      - "5318:4318"  # OTLP HTTP
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file:
      - ../.dev.env
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - backend

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"      # OTLP gRPC
      - "4318:4318"      # OTLP HTTP
      - "8889:8889"      # Prometheus metrics endpoint
    volumes:
      - ./monitoring/otel/otel-config.yaml:/etc/otel/otel-config.yml:ro
    command: [ "--config", "/etc/otel/otel-config.yml" ]
    networks:
      - backend

volumes:
  grafana_data:
  tempo_data:

networks:
  backend:
    driver: bridge